name: RobustFastAttentionXML

model:
  hidden_size: 256
  layers_num: 1
  linear_size: [256]
  dropout: 0.5
  emb_trainable: False
  level: 1

train:
  batch_size: 40
  nb_epoch: 30
  swa_warmup: 10

valid:
  batch_size: 40

predict:
  batch_size: 40
  k: 10

path: models

cluster:
  method: kmeans
  model_dir: models/clusters
  depth: 2
  max_leaf: 100
